### ISSUE TITLE
can not show box and line like the demo video in youtube?

### ISSUE THREAD

**Issue by jcyhcs** [Tinker-Twins/AprilTag#1]
hi,professor, i clone your code ,then i test with command:

i got nothing box and lines, what is the problem? please help me!

**Comment by Tinker-Twins** [comment]
This doesn't seem to be a problem. You seem to have executed the binary of C++ implementation, which is meant for embedded applications and thus only supports highlighting the detected AprilTag marker(s) as a part of visualization (it does not support advanced visualization features like boxes or axes). You will have to use the Python wrapper for generating the advanced annotations (refer [this](https://github.com/Tinker-Twins/AprilTag#python) section of README for further details).
