### ISSUE TITLE
Pose matrix

### ISSUE THREAD

**Issue by KshitijKarnawat** [Tinker-Twins/AprilTag#2]
Hi,

I need to plot the x,y and z values from the pose matrix to find and reduce the error after camera calibration by applying filters depending on the error observed.

Could you help me how I can have the pose matrix to accessible in a second script (detection script) and make changes or perform functions on it instead of just having it printed to the terminal (wrapper is priting it directly need it in the detection script).

Thanks

**Comment by Tinker-Twins** [comment]
The pose matrix is already accessible in the detection script (e.g. [apriltag_image.py](https://github.com/Tinker-Twins/AprilTag/blob/main/scripts/apriltag_image.py) in this repository) once you import the `apriltag` Python wrapper in your script and store the detection results in appropriate variables (e.g. like [this](https://github.com/Tinker-Twins/AprilTag/blob/main/scripts/apriltag_image.py#L43)).

The [result](https://github.com/Tinker-Twins/AprilTag/blob/main/scripts/apriltag.py#L665) variable contains `detection`, `pose`, `e0` and `e1` data for each of the detected tags. Therefore, in your detection script, you can simply use a nested for loop inside the [parent for loop](https://github.com/Tinker-Twins/AprilTag/blob/main/scripts/apriltag_image.py#L37) to extract the pose of each tag (described as a 4 x 4 homogeneous transformation matrix) and use it for your application.

You can use the following snippet as a reference to extract pose data of each tag (and print it separately from your detection script), as explained above:
```python
j = 1
for i in range(int(len(result)/4)):
    print(result[j])
    j += 4
```
Following is a screenshot of the implementation for easier understanding. We have tested the results by temporarily modifying the [apriltag_image.py](https://github.com/Tinker-Twins/AprilTag/blob/main/scripts/apriltag_image.py) script contained within this repository.

![Screenshot](https://user-images.githubusercontent.com/40835293/137112905-759df4e2-8826-4420-ab4c-d42039bb8329.png)

**Comment by KshitijKarnawat** [comment]
Thanks. This helps a lot now I can extract the X, Y, and Z values from the 4x4 Matrix for sensor fusion.

**Comment by KshitijKarnawat** [comment]
Hi @Tinker-Twins,

Sorry to reopen this post.

Can you tell me how do I get the roll pitch and yaw values from the 4x4 pose matrix.

is the internal 3x3 matrix a rotation matrix or can the values be directly extracted like in the case of X, Y, and Z.

**Comment by Tinker-Twins** [comment]
As discussed in the earlier comment, the result is a 4 x 4 homogeneous transformation matrix. Yes, the internal 3 x 3 matrix is a standard rotation matrix, followed by a 3 x 1 translation vector. The last row of the 4 x 4 matrix contains a 1 x 3 perspective projection matrix followed by a 1 x 1 scaling factor. Please refer the following figure:

![Homogeneous Transformation Matrix](https://user-images.githubusercontent.com/40835293/138428738-1b1300c3-4d77-417a-844e-2cc3d664d706.png)

**Comment by Tinker-Twins** [comment]
Additionally, we've created a separate repository yesterday, which hosts the function to convert a 3 x 3 rotation matrix into its Euler angle (i.e. roll, pitch, yaw) equivalent. You can find it [here](https://github.com/Tinker-Twins/RM2EA).

**Comment by KshitijKarnawat** [comment]
Thank you. Greatly appreciate the quick replies
