### ISSUE TITLE
Coordinate System

### ISSUE THREAD

**Issue by yyashpatel** [Tinker-Twins/AprilTag#4]
Hello,

I had a few questions about the representations -

1.  the pose matrix from the result variable (https://github.com/Tinker-Twins/AprilTag/blob/main/scripts/apriltag.py#L665) - it represents the pose of the april Tag with respect to the camera ?

2.  And if I inverse the pose matrix it will give the pose of the camera with respect to the april Tag ?

3.  how is the april Tag coordinate frame (xyz direction) represented and is it at the center of the tag ?

Thanks

**Comment by Tinker-Twins** [comment]
Following are the answers to your questions:

1. The `pose` result will return a 4x4 homogeneous transformation matrix of the AprilTag marker w.r.t. camera, for all detected markers in camera's FOV.
  ![Homogeneous Transform](https://github.com/Tinker-Twins/AprilTag/assets/40835293/ed2fdf80-ff7a-4515-87ed-466c3f9cfa22)
2. Inverse transformation of homogeneous transformation matrix returned by the `pose` result will in fact describe the relative pose of camera w.r.t. AprilTag marker.
3. The frame for AprilTag marker(s) is assigned at the center of each marker `x-axis` (red color) pointing towards right, `y-axis` (green color) pointing forward and `z-axis` (blue color) pointing upward (out of the plane).
  ![Axis Convention](https://github.com/Tinker-Twins/AprilTag/assets/40835293/b5840bd1-3756-49c2-ae6b-77c5426f8bf2)

Hope this helps, all the best!
